name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - app/*/src/**
      - app/*/package.json
      - .github/workflows/**
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn run build:app
