name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - packages/*/src/**
      - packages/*/package.json
      - package.json
      - jest.config.js
      - .github/workflows/test.yml
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn run test
      
      - name: Build test
        run: yarn run build:package
